/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  publishedAt: string;
  excerpt: string;
  body: SimplePortableText;
};

export type SimplePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type Specialty = {
  _id: string;
  _type: "specialty";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  details?: Array<string>;
  order: number;
  active?: boolean;
};

export type FaqPage = {
  _id: string;
  _type: "faqPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heading: string;
  intro?: string;
  items: Array<
    {
      _key: string;
    } & FaqItem
  >;
  cta?: Cta;
  ctaBackgroundImage?: ImageWithAlt;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ImageWithAlt = {
  _type: "imageWithAlt";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  alt?: string;
};

export type Cta = {
  _type: "cta";
  heading?: string;
  body?: string;
  label: string;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  headerBackgroundImage?: ImageWithAlt;
  process?: {
    eyebrow?: string;
    heading?: string;
    steps?: Array<
      {
        _key: string;
      } & ProcessStep
    >;
  };
};

export type PageHeader = {
  _type: "pageHeader";
  eyebrow?: string;
  heading: string;
  intro?: string;
};

export type PricingPage = {
  _id: string;
  _type: "pricingPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  fees?: {
    heading?: string;
    items?: Array<
      {
        _key: string;
      } & FeeItem
    >;
    note?: string;
  };
  insurance?: {
    heading?: string;
    body?: SimplePortableText;
  };
  cta?: Cta;
  ctaBackgroundImage?: ImageWithAlt;
};

export type SpecialtyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "specialty";
};

export type SpecialtiesPage = {
  _id: string;
  _type: "specialtiesPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: PageHeader;
  specialties?: Array<
    {
      _key: string;
    } & SpecialtyReference
  >;
  modality?: {
    eyebrow?: string;
    heading?: string;
    body?: SimplePortableText;
    backgroundImage?: ImageWithAlt;
  };
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  credentials?: string;
  heading: string;
  portraitImage?: ImageWithAlt;
  intro?: SimplePortableText;
  credentialGroups?: Array<
    {
      _key: string;
    } & CredentialGroup
  >;
  space?: TherapySpaceSection;
  philosophy?: QuoteSection;
};

export type QuoteSection = {
  _type: "quoteSection";
  eyebrow?: string;
  quote: string;
  attribution?: string;
  backgroundImage?: ImageWithAlt;
};

export type TherapySpaceSection = {
  _type: "therapySpaceSection";
  eyebrow?: string;
  heading: string;
  body?: string;
  exteriorImage?: ImageWithAlt;
  interiorImage?: ImageWithAlt;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  hero: {
    kicker?: string;
    heading: string;
    body?: string;
    ctaLabel?: string;
    backgroundImage?: ImageWithAlt;
  };
  specialtiesSection?: {
    eyebrow?: string;
    heading?: string;
    specialties?: Array<
      {
        _key: string;
      } & SpecialtyReference
    >;
  };
  aboutPreview?: {
    eyebrow?: string;
    heading?: string;
    body?: string;
    ctaLabel?: string;
    portraitImage?: ImageWithAlt;
  };
  ctaSection?: {
    heading?: string;
    body?: string;
    ctaLabel?: string;
    backgroundImage?: ImageWithAlt;
  };
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  legalName: string;
  practitioner: string;
  email: string;
  phone?: string;
  address: Address;
  hours: Array<string>;
  portalUrl?: string;
  url?: string;
  tagline?: string;
  areaServed?: Array<string>;
};

export type Address = {
  _type: "address";
  line1: string;
  line2: string;
  note?: string;
};

export type FaqItem = {
  _type: "faqItem";
  question: string;
  answer: Array<string>;
};

export type FeeItem = {
  _type: "feeItem";
  label: string;
  detail: string;
  price: string;
};

export type ProcessStep = {
  _type: "processStep";
  number: string;
  title: string;
  body: string;
};

export type CredentialGroup = {
  _type: "credentialGroup";
  heading: string;
  items: Array<
    {
      _key: string;
    } & CredentialItem
  >;
  license?: string;
};

export type CredentialItem = {
  _type: "credentialItem";
  title: string;
  detail: string;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | Post
  | SimplePortableText
  | Slug
  | Specialty
  | FaqPage
  | SanityImageAssetReference
  | ImageWithAlt
  | Cta
  | ContactPage
  | PageHeader
  | PricingPage
  | SpecialtyReference
  | SpecialtiesPage
  | AboutPage
  | QuoteSection
  | TherapySpaceSection
  | HomePage
  | SiteSettings
  | Address
  | FaqItem
  | FeeItem
  | ProcessStep
  | CredentialGroup
  | CredentialItem
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/lib/cms.ts
// Variable: siteSettingsQuery
// Query: *[_type == "siteSettings" && _id == "siteSettings"][0]{    name,    legalName,    practitioner,    email,    phone,    address,    hours,    portalUrl,    url,    tagline,    areaServed  }
export type SiteSettingsQueryResult = {
  name: string;
  legalName: string;
  practitioner: string;
  email: string;
  phone: string | null;
  address: Address;
  hours: Array<string>;
  portalUrl: string | null;
  url: string | null;
  tagline: string | null;
  areaServed: Array<string> | null;
} | null;

// Source: src/lib/cms.ts
// Variable: specialtiesQuery
// Query: *[_type == "specialty" && active != false] | order(order asc, title asc) {    "_key": _id,    title,    "slug": slug.current,    summary,    details  }
export type SpecialtiesQueryResult = Array<{
  _key: string;
  title: string;
  slug: string;
  summary: string;
  details: Array<string> | null;
}>;

// Source: src/lib/cms.ts
// Variable: homePageQuery
// Query: *[_type == "homePage" && _id == "homePage"][0]{    hero{      kicker,      heading,      body,      ctaLabel,      backgroundImage{        asset->{          _id,          url,          metadata {            dimensions {width, height},            lqip          }        },        alt,        crop,        hotspot      }    },    specialtiesSection{      eyebrow,      heading,      specialties[]->{        title,        "slug": slug.current,        summary,        details      }    },    aboutPreview{      eyebrow,      heading,      body,      ctaLabel,      portraitImage{        asset->{          _id,          url,          metadata {            dimensions {width, height},            lqip          }        },        alt,        crop,        hotspot      }    },    ctaSection{      heading,      body,      ctaLabel,      backgroundImage{        asset->{          _id,          url,          metadata {            dimensions {width, height},            lqip          }        },        alt,        crop,        hotspot      }    }  }
export type HomePageQueryResult = {
  hero: {
    kicker: string | null;
    heading: string;
    body: string | null;
    ctaLabel: string | null;
    backgroundImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  };
  specialtiesSection: {
    eyebrow: string | null;
    heading: string | null;
    specialties: Array<{
      title: string;
      slug: string;
      summary: string;
      details: Array<string> | null;
    }> | null;
  } | null;
  aboutPreview: {
    eyebrow: string | null;
    heading: string | null;
    body: string | null;
    ctaLabel: string | null;
    portraitImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  ctaSection: {
    heading: string | null;
    body: string | null;
    ctaLabel: string | null;
    backgroundImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: src/lib/cms.ts
// Variable: aboutPageQuery
// Query: *[_type == "aboutPage" && _id == "aboutPage"][0]{    credentials,    heading,    portraitImage{      asset->{        _id,        url,        metadata {          dimensions {width, height},            lqip        }      },      alt,      crop,      hotspot    },    intro,    credentialGroups[]{      _key,      heading,      items[]{_key, title, detail},      license    },    space{      eyebrow,      heading,      body,      exteriorImage{        asset->{          _id,          url,          metadata {            dimensions {width, height},            lqip          }        },        alt,        crop,        hotspot      },      interiorImage{        asset->{          _id,          url,          metadata {            dimensions {width, height},            lqip          }        },        alt,        crop,        hotspot      }    },    philosophy{      eyebrow,      quote,      attribution,      backgroundImage{        asset->{          _id,          url,          metadata {            dimensions {width, height},            lqip          }        },        alt,        crop,        hotspot      }    }  }
export type AboutPageQueryResult = {
  credentials: string | null;
  heading: string;
  portraitImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  intro: SimplePortableText | null;
  credentialGroups: Array<{
    _key: string;
    heading: string;
    items: Array<{
      _key: string;
      title: string;
      detail: string;
    }>;
    license: string | null;
  }> | null;
  space: {
    eyebrow: string | null;
    heading: string;
    body: string | null;
    exteriorImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
    interiorImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
  philosophy: {
    eyebrow: string | null;
    quote: string;
    attribution: string | null;
    backgroundImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: src/lib/cms.ts
// Variable: specialtiesPageQuery
// Query: *[_type == "specialtiesPage" && _id == "specialtiesPage"][0]{    header,    specialties[]->{      title,      "slug": slug.current,      summary,      details    },    modality{      eyebrow,      heading,      body,      backgroundImage{        asset->{          _id,          url,          metadata {            dimensions {width, height},            lqip          }        },        alt,        crop,        hotspot      }    }  }
export type SpecialtiesPageQueryResult = {
  header: PageHeader | null;
  specialties: Array<{
    title: string;
    slug: string;
    summary: string;
    details: Array<string> | null;
  }> | null;
  modality: {
    eyebrow: string | null;
    heading: string | null;
    body: SimplePortableText | null;
    backgroundImage: {
      asset: {
        _id: string;
        url: string;
        metadata: {
          dimensions: {
            width: number;
            height: number;
          } | null;
          lqip: string | null;
        } | null;
      } | null;
      alt: string | null;
      crop: SanityImageCrop | null;
      hotspot: SanityImageHotspot | null;
    } | null;
  } | null;
} | null;

// Source: src/lib/cms.ts
// Variable: pricingPageQuery
// Query: *[_type == "pricingPage" && _id == "pricingPage"][0]{    header,    fees{      heading,      items[]{_key, label, detail, price},      note    },    insurance{      heading,      body    },    cta,    ctaBackgroundImage{      asset->{        _id,        url,        metadata {          dimensions {width, height},            lqip        }      },      alt,      crop,      hotspot    }  }
export type PricingPageQueryResult = {
  header: PageHeader | null;
  fees: {
    heading: string | null;
    items: Array<{
      _key: string;
      label: string;
      detail: string;
      price: string;
    }> | null;
    note: string | null;
  } | null;
  insurance: {
    heading: string | null;
    body: SimplePortableText | null;
  } | null;
  cta: Cta | null;
  ctaBackgroundImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: src/lib/cms.ts
// Variable: contactPageQuery
// Query: *[_type == "contactPage" && _id == "contactPage"][0]{    header,    headerBackgroundImage{      asset->{        _id,        url,        metadata {          dimensions {width, height},            lqip        }      },      alt,      crop,      hotspot    },    process{      eyebrow,      heading,      steps[]{_key, number, title, body}    }  }
export type ContactPageQueryResult = {
  header: PageHeader | null;
  headerBackgroundImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
  process: {
    eyebrow: string | null;
    heading: string | null;
    steps: Array<{
      _key: string;
      number: string;
      title: string;
      body: string;
    }> | null;
  } | null;
} | null;

// Source: src/lib/cms.ts
// Variable: faqPageQuery
// Query: *[_type == "faqPage" && _id == "faqPage"][0]{    heading,    intro,    items[]{_key, question, answer},    cta,    ctaBackgroundImage{      asset->{        _id,        url,        metadata {          dimensions {width, height},            lqip        }      },      alt,      crop,      hotspot    }  }
export type FaqPageQueryResult = {
  heading: string;
  intro: string | null;
  items: Array<{
    _key: string;
    question: string;
    answer: Array<string>;
  }>;
  cta: Cta | null;
  ctaBackgroundImage: {
    asset: {
      _id: string;
      url: string;
      metadata: {
        dimensions: {
          width: number;
          height: number;
        } | null;
        lqip: string | null;
      } | null;
    } | null;
    alt: string | null;
    crop: SanityImageCrop | null;
    hotspot: SanityImageHotspot | null;
  } | null;
} | null;

// Source: src/lib/cms.ts
// Variable: blogPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {    _updatedAt,    title,    "slug": slug.current,    publishedAt,    excerpt,    body  }
export type BlogPostsQueryResult = Array<{
  _updatedAt: string;
  title: string;
  slug: string;
  publishedAt: string;
  excerpt: string;
  body: SimplePortableText;
}>;

// Source: src/lib/cms.ts
// Variable: blogPostQuery
// Query: *[_type == "post" && slug.current == $slug][0] {    _updatedAt,    title,    "slug": slug.current,    publishedAt,    excerpt,    body  }
export type BlogPostQueryResult = {
  _updatedAt: string;
  title: string;
  slug: string;
  publishedAt: string;
  excerpt: string;
  body: SimplePortableText;
} | null;

// Source: src/lib/cms.ts
// Variable: blogPostMetaQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {    _updatedAt,    title,    "slug": slug.current,    publishedAt,    excerpt,    body  }
export type BlogPostMetaQueryResult = Array<{
  _updatedAt: string;
  title: string;
  slug: string;
  publishedAt: string;
  excerpt: string;
  body: SimplePortableText;
}>;

// Source: src/lib/cms.ts
// Variable: blogPostSlugsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {    "slug": slug.current  }
export type BlogPostSlugsQueryResult = Array<{
  slug: string;
}>;

// Source: src/lib/cms.ts
// Variable: sitemapEntriesQuery
// Query: {    "pages": *[_id in ["homePage", "aboutPage", "specialtiesPage", "pricingPage", "contactPage", "faqPage"]]{      _id,      _updatedAt    },    "posts": *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {      _updatedAt,      "slug": slug.current    }  }
export type SitemapEntriesQueryResult = {
  pages: Array<{
    _id: string;
    _updatedAt: string;
  }>;
  posts: Array<{
    _updatedAt: string;
    slug: string;
  }>;
};

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  *[_type == "siteSettings" && _id == "siteSettings"][0]{\n    name,\n    legalName,\n    practitioner,\n    email,\n    phone,\n    address,\n    hours,\n    portalUrl,\n    url,\n    tagline,\n    areaServed\n  }\n': SiteSettingsQueryResult;
    '\n  *[_type == "specialty" && active != false] | order(order asc, title asc) {\n    "_key": _id,\n    title,\n    "slug": slug.current,\n    summary,\n    details\n  }\n': SpecialtiesQueryResult;
    '\n  *[_type == "homePage" && _id == "homePage"][0]{\n    hero{\n      kicker,\n      heading,\n      body,\n      ctaLabel,\n      backgroundImage{\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions {width, height},\n            lqip\n          }\n        },\n        alt,\n        crop,\n        hotspot\n      }\n    },\n    specialtiesSection{\n      eyebrow,\n      heading,\n      specialties[]->{\n        title,\n        "slug": slug.current,\n        summary,\n        details\n      }\n    },\n    aboutPreview{\n      eyebrow,\n      heading,\n      body,\n      ctaLabel,\n      portraitImage{\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions {width, height},\n            lqip\n          }\n        },\n        alt,\n        crop,\n        hotspot\n      }\n    },\n    ctaSection{\n      heading,\n      body,\n      ctaLabel,\n      backgroundImage{\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions {width, height},\n            lqip\n          }\n        },\n        alt,\n        crop,\n        hotspot\n      }\n    }\n  }\n': HomePageQueryResult;
    '\n  *[_type == "aboutPage" && _id == "aboutPage"][0]{\n    credentials,\n    heading,\n    portraitImage{\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {width, height},\n            lqip\n        }\n      },\n      alt,\n      crop,\n      hotspot\n    },\n    intro,\n    credentialGroups[]{\n      _key,\n      heading,\n      items[]{_key, title, detail},\n      license\n    },\n    space{\n      eyebrow,\n      heading,\n      body,\n      exteriorImage{\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions {width, height},\n            lqip\n          }\n        },\n        alt,\n        crop,\n        hotspot\n      },\n      interiorImage{\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions {width, height},\n            lqip\n          }\n        },\n        alt,\n        crop,\n        hotspot\n      }\n    },\n    philosophy{\n      eyebrow,\n      quote,\n      attribution,\n      backgroundImage{\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions {width, height},\n            lqip\n          }\n        },\n        alt,\n        crop,\n        hotspot\n      }\n    }\n  }\n': AboutPageQueryResult;
    '\n  *[_type == "specialtiesPage" && _id == "specialtiesPage"][0]{\n    header,\n    specialties[]->{\n      title,\n      "slug": slug.current,\n      summary,\n      details\n    },\n    modality{\n      eyebrow,\n      heading,\n      body,\n      backgroundImage{\n        asset->{\n          _id,\n          url,\n          metadata {\n            dimensions {width, height},\n            lqip\n          }\n        },\n        alt,\n        crop,\n        hotspot\n      }\n    }\n  }\n': SpecialtiesPageQueryResult;
    '\n  *[_type == "pricingPage" && _id == "pricingPage"][0]{\n    header,\n    fees{\n      heading,\n      items[]{_key, label, detail, price},\n      note\n    },\n    insurance{\n      heading,\n      body\n    },\n    cta,\n    ctaBackgroundImage{\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {width, height},\n            lqip\n        }\n      },\n      alt,\n      crop,\n      hotspot\n    }\n  }\n': PricingPageQueryResult;
    '\n  *[_type == "contactPage" && _id == "contactPage"][0]{\n    header,\n    headerBackgroundImage{\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {width, height},\n            lqip\n        }\n      },\n      alt,\n      crop,\n      hotspot\n    },\n    process{\n      eyebrow,\n      heading,\n      steps[]{_key, number, title, body}\n    }\n  }\n': ContactPageQueryResult;
    '\n  *[_type == "faqPage" && _id == "faqPage"][0]{\n    heading,\n    intro,\n    items[]{_key, question, answer},\n    cta,\n    ctaBackgroundImage{\n      asset->{\n        _id,\n        url,\n        metadata {\n          dimensions {width, height},\n            lqip\n        }\n      },\n      alt,\n      crop,\n      hotspot\n    }\n  }\n': FaqPageQueryResult;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    body\n  }\n':
      BlogPostsQueryResult | BlogPostMetaQueryResult;
    '\n  *[_type == "post" && slug.current == $slug][0] {\n    _updatedAt,\n    title,\n    "slug": slug.current,\n    publishedAt,\n    excerpt,\n    body\n  }\n': BlogPostQueryResult;
    '\n  *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n    "slug": slug.current\n  }\n': BlogPostSlugsQueryResult;
    '\n  {\n    "pages": *[_id in ["homePage", "aboutPage", "specialtiesPage", "pricingPage", "contactPage", "faqPage"]]{\n      _id,\n      _updatedAt\n    },\n    "posts": *[_type == "post" && defined(slug.current)] | order(publishedAt desc) {\n      _updatedAt,\n      "slug": slug.current\n    }\n  }\n': SitemapEntriesQueryResult;
  }
}
